from django.urls import path
from agriculture import views

urlpatterns = [
    path('', views.index, name='home'),
    path('login', views.login, name='login'),
    path('login1', views.login1, name='login1'),
    path('logout', views.logout, name='logout'),
    path('AdminHomePage', views.AdminHomePage, name='admin_home'),
    path('view_farmer_request', views.view_farmer_request, name='view_farmer_request'),
    path('approveFarm/<str:sid>', views.approveFarm, name='approve_farm'),
    path('deletefarmersre/<str:sid>', views.deletefarmersre, name='delete_farmer_request'),
    path('view_approved_farmer', views.view_approved_farmer, name='view_approved_farmer'),
    path('deletefarmer/<str:sid>', views.deletefarmer, name='delete_farmer'),
    path('addCategory', views.addCategory, name='add_category'),
    path('viewCategory', views.viewCategory, name='view_category'),
    path('deleteCategory/<int:id>', views.deleteCategory, name='delete_category'),
    path('editCategory/<int:id>', views.editCategory, name='edit_category'),
    path('updatecategory/<int:id>', views.updatecategory, name='update_category'),
    path('admin_products_request', views.admin_products_request, name='admin_products_request'),
    path('approvesell/<int:id>', views.approvesell, name='approve_sell'),
    path('ViewFarmerProductApproved', views.ViewFarmerProductApproved, name='view_farmer_product_approved'),
    path('viewbookingitems', views.viewbookingitems, name='view_booking_items'),
    path('ViewcompliantAdmin', views.ViewcompliantAdmin, name='view_compliant_admin'),
    path('Reply/<int:id>', views.Reply, name='reply_complaint'),
    path('FarmerHome', views.FarmerHome, name='farmer_home'),
    path('register_farmer', views.register_farmer, name='register_farmer'),
    path('viewProductCategoryFarmer', views.viewProductCategoryFarmer, name='view_category_farmer'),
    path('AddFarmerproduct/<int:id>/<str:pid>', views.AddFarmerproduct,     name='add_farmer_product'),
    path('viewFarmeraddeditem', views.viewFarmeraddeditem, name='view_farmer_items'),
    path('Farmersellhistory', views.Farmersellhistory, name='farmer_sell_history'),
    path('UserHome', views.UserHome, name='user_home'),
    path('adduser', views.adduser, name='add_user'),
    path('viewProductCategoryUser', views.viewProductCategoryUser, name='view_category_user'),
    path('selctproducts/<int:id>/<str:sid>', views.selctproducts,           name='select_products'),
    path('Purchase/<int:id>/<int:qid>', views.Purchase, name='purchase'),
    path('Viewcart', views.Viewcart, name='view_cart'),
    path('deleteCart/<int:id>', views.deleteCart, name='delete_cart'),
    path('Bank', views.Bank, name='bank_payment'),
    path('Userhistory', views.Userhistory, name='user_history'),
    path('Sendcompliant', views.Sendcompliant, name='send_complaint'),
    path('Viewcompliant', views.Viewcompliant, name='view_complaint'),
]
